// const sync = require('./models/sync');
// sync();

const express = require('express');
const morgan = require('morgan');
const dotenv = require('dotenv');
dotenv.config();
const port = process.env.PORT || 3000;
const app = express();
const memberRouter = require('./routers/memberRouter');
const pillRouter = require('./routers/pillRouter');
const imageRouter = require('./routers/imageRouter');
const prescriptionRouter = require('./routers/prescriptionRouter');
const receiptRouter = require('./routers/receiptRouter');
const checkAuth = require('./routers/authorization');
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/pills', checkAuth);
app.use('/pills', pillRouter);
app.use('/members', memberRouter);
app.use('/images', imageRouter);
app.use('/prescription', checkAuth);
app.use('/prescription', prescriptionRouter);
app.use('/receipt', checkAuth);
app.use('/receipt', receiptRouter);
app.use((_, res) => {
    res.status(404).json({success: false, token: '', message: '요청이 잘못됨'});
});
app.listen(port);